version: '3'

services:
  php-env:
    build: .
    volumes:  
      - ./src:var/www/html
    ports:
      - 9000:80

  mysqldb:
    image: mysql:latest
    restart: always
    ports:
      - '3307:3306'
    environment:
      - MYSQL_ROOT_PASSWORD=root

  phpmyadmin:
    image: phpmyadmin:latest
    restart: always
    ports:
      - 9001:80
    environment:
      - PMA_ARBITRARY=1